### PR TITLE
Fix ListAdvertisedRoutes

### PR DESCRIPTION
**Pull request by p-strusiewiczsurmacki-mobica**
After merging #1584 (I think) build in the CI fails with

```
Error: 54.21 pkg/bgp/server.go:113:18: undefined: api.TableType_GLOBAL
Error: 54.21 pkg/bgp/server.go:119:32: too many arguments in call to b.s.ListPath
54.21 	have (context.Context, *"github.com/osrg/gobgp/v4/api".ListPathRequest, func(destination *"github.com/osrg/gobgp/v4/api".Destination))
54.21 	want (apiutil.ListPathRequest, func(prefix "github.com/osrg/gobgp/v4/pkg/packet/bgp".NLRI, paths []*apiutil.Path))
74.77 make: *** [Makefile:27: kube-vip] Error 1
```

I have thrown together a quick fix for this, however **THIS WAS NOT TESTED**.

### CODE REVIEW

**Comment by thebsdbox** [comment]
Odd, how did it pass CI earlier. I've just about added in BFD functionality into kube-vip. I'll test this with my local BGP router.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
> Odd, how did it pass CI earlier

#1584 was merged before #1585

I think that #1585 which added this function was created with gobgp v3 libraries, and passed the CI, but #1584 was merged and the CI was not restarted with gobgp v4 for #1585.

**Review by thebsdbox — APPROVED** [review]
fixes the dep issue.
